### ISSUE TITLE
Feedback/FreeBSD port created

### ISSUE THREAD

**Issue by ehaupt** [spook/sshping#1]
I really like that tool and wanted to let you know that I've added a [FreeBSD port](https://www.freshports.org/net/sshping/).

FreeBSD users can now install sshping like so:

    pkg install sshping

Could you please tag an initial release (eg.: v0.1) so I won't have to reference a particular commit?

Nice to have:
- man page

Thanks for the great piece of software!

**Comment by spook** [comment]
@ehaupt Thanx for the feedback and the port.  And my apologies for the late response.  I've tagged a release v0.1.0 .  Man page coming soon... since I don't include any installers I'll do it in POD then you can use tools like pod2man to convert.

**Comment by spook** [comment]
@ehaupt Source for man page added.  Lemme know if you find any mistakes etc in it.  Thanx.
