### ISSUE TITLE
Possible AUR Package

### ISSUE THREAD

**Issue by blu3r4d0n** [spook/sshping#11]
Would you mind if I packaged this for the AUR?

**Comment by ericcurtin** [comment]
@spook is off for a few days. I'll poke him when he gets back. I'm sure he would be delighted if you packaged this for AUR. A colleague of mine is also working on Windows support at present.

**Comment by blu3r4d0n** [comment]
@ericcurtin Awesome! I'll go ahead and get this packaged. I would really like to see this in more places. It's a great tool.

**Comment by spook** [comment]
@blu3r4d0n Yep, that would be great -- thanx for doing it.  Feel free to update the README.md with the AUR/arch pointer etc.
@ericcurtin Thanx for covering for me while I was out.
