### ISSUE TITLE
results in human readable format mins, kbps,mbps..

### ISSUE THREAD

**Issue by akhilin** [spook/sshping#14]

**Comment by spook** [comment]
Hello @akhilin,
I'm unsure what you are asking or reporting with this issue.  Would you please clarify?
Thanx,
-- Uncle Spook

**Comment by akhilin** [comment]
it would be great if the results are shown in nsec->mins,hours and bytes-> Mbps,Gbps

# bin/sshping -d cheyenne.example.com
ssh-Login-Time:    1,733,748,227 nsec
Minimum-Latency:         847,107 nsec
Median-Latency:          996,029 nsec
Average-Latency:         992,186 nsec
Average-Deviation:        67,079 nsec
Maximum-Latency:       1,289,470 nsec
Echo-Count:                1,000 Bytes
Upload-Size:           8,000,000 Bytes
Upload-Rate:           4,732,718 Bytes/second
Download-Size:         8,000,000 Bytes
Download-Rate:         3,781,725 Bytes/second

**Comment by Jay2k1** [comment]
Agreed, maybe with `-H` switch for `--human-readable` or something. On a recent test I got
> ssh-Login-Time:    7,572,119,994 nsec

That's a lot of nanoseconds. This would look nicer:
> ssh-Login-Time:    7.572 seconds

**Comment by spook** [comment]
What?! You don't have your wallclock at home set to display decimal nanoseconds since the epoch?  Shocking! ;-)

I think I'll go with -h (lowercase) and --human-readable for the switch.  That's what other utilities use, such as `df` or `ls`.

**Comment by spook** [comment]
Here's a first pass at human format output, along with delimited and default formats.  Is this what you had in mind?

### Default Format
```
$ bin/sshping localhost 
ssh-Login-Time:       1849103800 nsec
Minimum-Latency:           67149 nsec
Median-Latency:            91769 nsec
Average-Latency:           96336 nsec
Average-Deviation:         27287 nsec
Maximum-Latency:          427796 nsec
Echo-Count:                 1000 Bytes
Upload-Size:             8000000 Bytes
Upload-Rate:            38569601 Bytes/sec
Download-Size:           8000000 Bytes
Download-Rate:           9538100 Bytes/sec
```
### Delimited Format
```
$ bin/sshping -d localhost 
ssh-Login-Time:    1,880,290,661 nsec
Minimum-Latency:          68,048 nsec
Median-Latency:           72,672 nsec
Average-Latency:          81,520 nsec
Average-Deviation:        21,796 nsec
Maximum-Latency:         469,856 nsec
Echo-Count:                1,000 Bytes
Upload-Size:           8,000,000 Bytes
Upload-Rate:          36,945,444 Bytes/sec
Download-Size:         8,000,000 Bytes
Download-Rate:        10,429,057 Bytes/sec
```
### Human-readable format (New)
```
$ bin/sshping -H localhost 
ssh-Login-Time:             1.84  sec
Minimum-Latency:            82.6 usec
Median-Latency:              101 usec
Average-Latency:             107 usec
Average-Deviation:          19.1 usec
Maximum-Latency:             365 usec
Echo-Count:                1.00 kBytes
Upload-Size:               8.00 MBytes
Upload-Rate:               37.7 MBytes/sec
Download-Size:             8.00 MBytes
Download-Rate:             9.95 MBytes/sec
```
Since it's rare for times to go higher than a few minutes, I see no reason to convert to hours:mins:secs for the bigger values.  Just seconds should be fine.

**Comment by akhilin** [comment]
That's perfect.

## Seconds: 
s - seconds
ms - milliseconds 
These are standard and easily understandable by anyone. So showing seconds in ```s or ms``` is what I recommend.

## Size is fine

**Comment by Jay2k1** [comment]
I like it! And personally, I don't care much about whether it's 's' or 'sec'.

**Comment by spook** [comment]
@akhilin Yeah I was wondering about going to SI standard abbreviations for the units, as I was typing in the code.  It's an easy change, I think I'll do it.

**Comment by spook** [comment]
Just about there, I have to fix an alignment problem still...

**Comment by spook** [comment]
I merged PR #17 even tho there's still some minor alignment issues.
I'll get that in another pass.

**Comment by akhilin** [comment]
Great Thanks.

**Comment by jcelerier** [comment]
Hey, would you mind tagging a release with that so that linux distros can pick it up ? thanks !
