### ISSUE TITLE
Remove three dash prefix from output?

### ISSUE THREAD

**Issue by spook** [spook/sshping#3]
Howdy all,
Do you think I should remove the three dashes (and leading spaces) from the output?  It's kinda non-standard, I'd rather use the simple RFC-2822 format. Removing them would also make parsing easier.

Please comment back if you care one way or the other.

Thanx,
-- Uncle Spook

This old example output:
```
---  ssh Login Time: 4,286,336,535 nsec
--- Minimum Latency:   134,679,785 nsec
---  Median Latency:   139,936,318 nsec  +/- 20,996,458 std dev
--- Average Latency:   145,943,038 nsec
--- Maximum Latency:   254,836,720 nsec
---      Echo count:         1,000 Bytes
---   Transfer Size:     8,000,000 Bytes
---   Transfer Rate:       250,622 Bytes/second
```
Would become:
```
ssh Login Time:  4,286,336,535 nsec
Minimum Latency:   134,679,785 nsec
Median Latency:    139,936,318 nsec  +/- 20,996,458 std dev
Average Latency:   145,943,038 nsec
Maximum Latency:   254,836,720 nsec
Echo count:              1,000 Bytes
Transfer Size:       8,000,000 Bytes
Transfer Rate:         250,622 Bytes/second
```

**Comment by ericcurtin** [comment]
Both are fine!

I agree number two is slighly easier to parse and there are less unneccessarys chars, the newline is enough to split each line. It's a bash one liner to remove the first word and leading whitespace from each line in the output.

**Comment by spook** [comment]
@ericcurtin  at al...
I decided I'll do this.  And, to make it even easier to parse, I'll use RFC-822 (now 2822) header format.  The output would look like this:
```
ssh-Login-Time:    1719630754 nsec
Minimum-Latency:       850850 nsec
Median-Latency:        994138 nsec  +/- 57598 std dev
Average-Latency:      1005456 nsec
Maximum-Latency:      1337097 nsec
Echo-Count:              1000 Bytes
Transfer-Size:        8000000 Bytes
Upload-Rate:          5124525 Bytes/second
```
While I'm at it, should I pull in the standard deviation to it's own line?

**Comment by spook** [comment]
Changes pushed up in a3651d4f57ca5e6b1821a94e0a219cb27840cb31
Look ok?  Note that "Transfer Rate" became "Upload-Rate", to clarify the direction.

**Comment by ericcurtin** [comment]
Whatever you think is best @spook

It is nice when they are on one line that you know that the standard deviation is relative to the median (I'm assuming based off the output)

Standard deviation is more commonly relative to the average. As long as it's not ambiguous whether it is relative to the mean or average, that's probably the main thing I think? Whether that means two lines or one, it depends... If it's a line between average and mean it would be unclear, otherwise it wouldn't be I guess...

**Comment by ericcurtin** [comment]
Looks great @spook

**Comment by spook** [comment]
@ericcurtin 
Since I like everything easy for scripts, I'll make standard deviation be on its own line.
And, you pointed out an error I had:  I put the std dev on the Median when it really was for the  average (the mean).  Oops!    I'll call it "Average-Deviation" so it's clear.

**Comment by spook** [comment]
Here's the new output, note the Average-Deviation field:
```
ssh-Login-Time:    1,733,748,227 nsec
Minimum-Latency:         847,107 nsec
Median-Latency:          996,029 nsec
Average-Latency:         992,186 nsec
Average-Deviation:        67,079 nsec
Maximum-Latency:       1,289,470 nsec
Echo-Count:                1,000 Bytes
Transfer-Size:         8,000,000 Bytes
Upload-Rate:           5,102,315 Bytes/second
```
And the man page description:
```
Average-Deviation
    The standard deviation on the average latency.  It quantifies
    how varied the latency is for each character's echo.  A lower
    number indicates a tighter grouping of latencies, a higher 
    number indicates more variation in the latencies.
    "One" standard deviation is the average plus or minus this amount.
```
Yeah, IANAMT (I am not a math teacher!)

**Comment by spook** [comment]
Closing this issue with commit d36dafb74a165c49abc01d891deb305efececba7
I'll make a new release too.
Thanx for the f/b!
