### ISSUE TITLE
Packaging...

### ISSUE THREAD

**Issue by ericcurtin** [spook/sshping#4]
If you change from plain old makefile to a CMake one, you get the .deb .rpm (and .msi if you wanted to join the dark side) packaging "for free" using it's CPack module, simple example:

https://github.com/ericcurtin/sxx/blob/master/CMakeLists.txt

There is an elegance to plain old makefiles I guess though. There is also an elegance to .tar.gz packages over .rpm/.deb. CMake also supports create .tar.gz packages and self extracting .tar.gz packages.

Or you could try something bleeding edge like Snappy or AppImage kit, which aims to solve the static linking, dynamic linking & packaging mess Linux has right now.

Maybe it's something you don't want to worry about right now.

**Comment by spook** [comment]
Thanx @ericcurtin, I've thought about packaging this as well.  Yet it's such a simple little binary... I dunno.  I'll think on it.

**Comment by ericcurtin** [comment]
Yeah I get ya... The target user likely knows how to compile and install a simple binary too... Maybe some quick and easy install steps in the readme might be the simplest option...

One thing I've been thinking about is seeing what the process is of getting one of these tools in the debian/fedora repos (and hence getting them into ubuntu and rhel repos eventually "for free"). To raise awareness of the tool and make it easier to install/update

Maybe there's too much red tape for there to cross to be worth it.

**Comment by spook** [comment]
Hi @ericcurtin  I've started a CMakeLists.txt, if you get a chance please review it.  It seems easy enough tho...

**Comment by ericcurtin** [comment]
The sshping CMakeLists.txt look great! :+1:  Although I didn't try to compile or generate packages with it. I'm sure it works fine!

Yeah it's pretty high level and fast, it generates Windows makefiles also, whatever they call them in Windows land. And Windows packages.

I could never go back to autotools, it's easier to write via cmake and generates makefiles faster. Portability is just an added benefit.

I've more stuff on my dev branch:

https://github.com/ericcurtin/sxx/blob/dev/CMakeLists.txt

It's 90% complete, it's to get the distro versions, cpu architectures, etc. in the filename, depends on how much you want to invest in packaging.

**Comment by spook** [comment]
@ericcurtin and others...
CMake build added, lemme know if you find any problems.  Thanx for the suggestion!
