### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by axot** [spook/sshping#5]
`error: 'opts' does not name a type` said by g++

**Comment by spook** [comment]
Hi @axot, what O/S and version did you get this from?

**Comment by ericcurtin** [comment]
My bad @spook 

Fix:

https://github.com/spook/sshping/pull/6

**Comment by spook** [comment]
Thanx @ericcurtin -- my bad also for not running it thru my test suite.  I've merged your PR but not closing this until I fire up the test lab and give it a full run.  I should get to that this week.

**Comment by spook** [comment]
OK, looks good.  Closing this, thanx for the report!
