### ISSUE TITLE
Add measuring of the download speed

### ISSUE THREAD

**Issue by ufechner7** [spook/sshping#7]
Hello,
Currently only the speed for transferring data to the server is measured. For me the download speed via scp would also be of interest (and it could be quite different because I use an 4G connection).
Thanks for your good work!
Uwe

**Comment by spook** [comment]
Hello @ufechner7  -

Let me check that I understand your request - are you asking to do the transfer test in the other direction?  Currently the transfer test is from sshping (client) to the server.  For server to client, I'd have to come up with a source of data...  Hmmmm, perhaps I could read from /dev/urandom.  I'll test that.

Thanx for the suggestion!
- Steve

**Comment by ericcurtin** [comment]
"For me the download speed via scp would also be of interest"

This would also be of interest to a certain project in HPE! Plus upload speed via scp. Although we already have tests for that.

Do you deem that as part of the scope of sshping? Maybe not a bad idea

It's easy to script to determine ssh/scp bandwidth. Not so much for ssh/scp latency though, which is what makes this tool useful.

**Comment by ericcurtin** [comment]
scpiperf doesn't have the same ring to it as sshping lol

**Comment by spook** [comment]
Yep, I think it would be part of sshping.  I have to figure out what the source file will be for the download.  I purposely did the upload to /dev/null so I wouldn't put a file on the server.  But if I can't find a way to limit the size of a download from /dev/urandom (or similar), I may have to let the upload file go into the filesystem, then use that to do the download.  And remove it when done.

**Comment by spook** [comment]
Started PR #8 for this.  Looks like the scp subsystem cannot read from /dev/urandom so I'll read back the file I sent for the upload test.

**Comment by spook** [comment]
I went ahead and merged the PR, so just try out the main branch and if you want changes, please open a new issue.  Thanx for submitting this!
